### ISSUE TITLE
Apifox接口设计

### ISSUE THREAD

**Issue by BiDuang** [Greedy-Nattinessers/Shop-BE#1]
在ApiFox内设计整个项目的接口以及其结构信息。

包含以下部分：
- [ ] 商城主页
- [ ] 搜索结果页
- [ ] 商品详情页
- [ ] 用户信息页

---

后端负责：
@xiao-kousaka @CenFongDusty @Starry-Sky-OUC @Sunsetalone

**Comment by xiao-kousaka** [comment]
第一版的api文档，仍有一些地方需要改进和商讨：
1. 只添加了购物车相关的说明，暂未处理类似的收藏等接口；
2. 将对后端需求文档的部分内容进行了拆分，如商品搜索与显示缩略图的功能被拆分；
3. 部分需求不合理，如按分类展示所有商品的功能可以并入搜索的部分；且没有关于主页信息的相关请求；
4. 部分内容不会（已标注）或细节没写到（如某些失败的返回值）。

# 文档正文
<html>
<body>
<!DOCTYPE html><pre cid="n0" mdtype="meta_block" class="md-meta-block md-end-block" style="box-sizing: border-box; overflow: hidden auto; font-family: var(--monospace); font-size: 13.6px; min-height: 0.8rem; white-space: pre-wrap; background: rgb(247, 247, 247); display: block; width: inherit; padding: 1rem; line-height: 1.45; border: 0px; border-radius: 3px; color: rgb(119, 119, 119); margin-top: 0px !important; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">title: Mall
language_tabs:
  - shell: Shell
  - http: HTTP
  - javascript: JavaScript
  - ruby: Ruby
  - python: Python
  - php: PHP
  - java: Java
  - go: Go
toc_footers: []
includes: []
search: true
code_clipboard: true
highlight_theme: darkula
headingLevel: 2
generator: "@tarslib/widdershins v4.0.23"

</pre><h1 cid="n2" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 2.25em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.2; cursor: text; padding-bottom: 0.3em; border-bottom: 1px solid rgb(238, 238, 238); white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Mall</span></h1><p cid="n3" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Base URLs:</span></p><h1 cid="n4" mdtype="heading" class="md-end-block md-heading md-focus" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 2.25em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.2; cursor: text; padding-bottom: 0.3em; border-bottom: 1px solid rgb(238, 238, 238); white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">Authentication</span></h1><h1 cid="n5" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 2.25em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.2; cursor: text; padding-bottom: 0.3em; border-bottom: 1px solid rgb(238, 238, 238); white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">用户信息</span></h1><h2 cid="n6" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.75em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.225; cursor: text; padding-bottom: 0.3em; border-bottom: 1px solid rgb(238, 238, 238); white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">POST 用户注册</span></h2><p cid="n7" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">POST /user/register</span></p><p cid="n8" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">用户请求注册一个商城账号</span></p><blockquote cid="n9" mdtype="blockquote" style="box-sizing: border-box; margin: 0.8em 0px; border-left: 4px solid rgb(223, 226, 229); padding: 0px 15px; color: rgb(119, 119, 119); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><p cid="n10" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Body 请求参数</span></p></blockquote><pre spellcheck="false" class="md-fences md-end-block ty-contain-cm modeLoaded" lang="yaml" cid="n11" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: var(--monospace); font-size: 0.9em; display: block; break-inside: avoid; text-align: left; white-space: normal; background-image: inherit; background-position: inherit; background-size: inherit; background-repeat: inherit; background-attachment: inherit; background-origin: inherit; background-clip: inherit; background-color: rgb(248, 248, 248); position: relative !important; border: 1px solid rgb(231, 234, 237); border-radius: 3px; padding: 8px 4px 6px; margin-bottom: 15px; margin-top: 15px; width: inherit; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-atom" style="box-sizing: border-box; color: rgb(34, 17, 153);">username</span><span class="cm-meta" style="box-sizing: border-box; color: rgb(85, 85, 85);">: </span>Yoshiki</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-atom" style="box-sizing: border-box; color: rgb(34, 17, 153);">password</span><span class="cm-meta" style="box-sizing: border-box; color: rgb(85, 85, 85);">: </span>k0p6th@feb25</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-atom" style="box-sizing: border-box; color: rgb(34, 17, 153);">email</span><span class="cm-meta" style="box-sizing: border-box; color: rgb(85, 85, 85);">: </span>me@sbga.com</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-atom" style="box-sizing: border-box; color: rgb(34, 17, 153);">captcha</span><span class="cm-meta" style="box-sizing: border-box; color: rgb(85, 85, 85);">: </span><span class="cm-string" style="box-sizing: border-box; color: rgb(170, 17, 17);">"135135"</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span></pre><h3 cid="n12" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.5em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.43; cursor: text; white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">请求参数</span></h3><figure class="md-table-fig" cid="n13" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
名称 | 位置 | 类型 | 必选 | 说明
-- | -- | -- | -- | --
body | body | object | 否 | none
» username | body | string | 是 | 用户请求注册的用户名称
» password | body | string | 是 | 用户请求注册的账户密码
» email | body | string | 是 | 用户请求注册的邮箱地址
» captcha | body | string | 是 | 发送给用户的邮箱验证码 //可能是多余的，应当放到验证码的部分里

</figure><br class="Apple-interchange-newline">
</body>
</html>---
title: Mall
language_tabs:
  - shell: Shell
  - http: HTTP
  - javascript: JavaScript
  - ruby: Ruby
  - python: Python
  - php: PHP
  - java: Java
  - go: Go
toc_footers: []
includes: []
search: true
code_clipboard: true
highlight_theme: darkula
headingLevel: 2
generator: "@tarslib/widdershins v4.0.23"


---

# Mall

Base URLs:

# Authentication

# 用户信息

## POST 用户注册

POST /user/register

用户请求注册一个商城账号

> Body 请求参数

```yaml
username: Yoshiki
password: k0p6th@feb25
email: me@sbga.com
captcha: "135135"

```

### 请求参数

| 名称       | 位置 | 类型   | 必选 | 说明                                                         |
| ---------- | ---- | ------ | ---- | ------------------------------------------------------------ |
| body       | body | object | 否   | none                                                         |
| » username | body | string | 是   | 用户请求注册的用户名称                                       |
| » password | body | string | 是   | 用户请求注册的账户密码                                       |
| » email    | body | string | 是   | 用户请求注册的邮箱地址                                       |
| » captcha  | body | string | 是   | 发送给用户的邮箱验证码 //可能是多余的，应当放到验证码的部分里 |

> 返回示例

> 201 Response

```json
{
  "token": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                                   | 说明 | 数据模型 |
| ------ | ------------------------------------------------------------ | ---- | -------- |
| 201    | [[Created](https://tools.ietf.org/html/rfc7231#section-6.3.2)](https://tools.ietf.org/html/rfc7231#section-6.3.2) | none | Inline   |
| 400    | [[Bad Request](https://tools.ietf.org/html/rfc7231#section-6.5.1)](https://tools.ietf.org/html/rfc7231#section-6.5.1) | none | Inline   |
| 422    | [[Unprocessable Entity](https://tools.ietf.org/html/rfc2518#section-10.3)](https://tools.ietf.org/html/rfc2518#section-10.3) | none | Inline   |

### 返回数据结构

状态码 **201**

| 名称    | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ------- | ------ | ---- | ---- | ------ | ---- |
| » token | string | true | none |        | none |

状态码 **400**

| 名称  | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ----- | ------ | ---- | ---- | ------ | ---- |
| » err | string | true | none |        | none |

状态码 **422**

| 名称  | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ----- | ------ | ---- | ---- | ------ | ---- |
| » err | string | true | none |        | none |

## POST 用户登录

POST /user/login

用户登录账号，需要用到邮箱及密码

> Body 请求参数

```yaml
email: reimilia@kop6th.win
password: "114514"

```

### 请求参数

| 名称       | 位置 | 类型   | 必选 | 说明               |
| ---------- | ---- | ------ | ---- | ------------------ |
| body       | body | object | 否   | none               |
| » email    | body | string | 否   | 用户请求登录的邮箱 |
| » password | body | string | 否   | 用户请求登录的密码 |

> 返回示例

> 200 Response

```json
{
  "token": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                                   | 说明 | 数据模型 |
| ------ | ------------------------------------------------------------ | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1)      | none | Inline   |
| 422    | [[Unprocessable Entity](https://tools.ietf.org/html/rfc2518#section-10.3)](https://tools.ietf.org/html/rfc2518#section-10.3) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称    | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ------- | ------ | ---- | ---- | ------ | ---- |
| » token | string | true | none |        | none |

状态码 **422**

| 名称  | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ----- | ------ | ---- | ---- | ------ | ---- |
| » err | string | true | none |        | none |

## POST 验证码

POST /user/token

本接口大概率由其他接口间接调用；
用户提供邮箱，后端生成验证码并发送给用户。

> Body 请求参数

```yaml
email: ""

```

### 请求参数

| 名称    | 位置 | 类型   | 必选 | 说明 |
| ------- | ---- | ------ | ---- | ---- |
| body    | body | object | 否   | none |
| » email | body | string | 否   | none |

> 返回示例

> 200 Response

```json
{
  "captcha": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称      | 类型   | 必选 | 约束 | 中文名 | 说明 |
| --------- | ------ | ---- | ---- | ------ | ---- |
| » captcha | string | true | none |        | none |

## GET 请求用户信息

GET /user/query

前端提供token，请求用户信息

### 请求参数

| 名称  | 位置  | 类型   | 必选 | 说明                      |
| ----- | ----- | ------ | ---- | ------------------------- |
| token | query | string | 否   | 用于请求用户信息的token值 |

> 返回示例

> 200 Response

```json
{
  "userid": "string",
  "username": "string",
  "email": "string",
  "password": "string",
  "sex": "string",
  "profile": {},
  "address": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称       | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ---------- | ------ | ---- | ---- | ------ | ---- |
| » userid   | string | true | none |        | none |
| » username | string | true | none |        | none |
| » email    | string | true | none |        | none |
| » password | string | true | none |        | none |
| » sex      | string | true | none |        | none |
| » profile  | object | true | none | 头像   | none |
| » address  | string | true | none |        | none |

## POST 修改密码

POST /user/password

用户请求验证码，通过后修改密码

> Body 请求参数

```yaml
captcha: "114514"
new_password: "114514"

```

### 请求参数

| 名称           | 位置 | 类型   | 必选 | 说明 |
| -------------- | ---- | ------ | ---- | ---- |
| body           | body | object | 否   | none |
| » captcha      | body | string | 否   | none |
| » new_password | body | string | 否   | none |

> 返回示例

> 200 Response

```json
{
  "token": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                                   | 说明 | 数据模型 |
| ------ | ------------------------------------------------------------ | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1)      | none | Inline   |
| 422    | [[Unprocessable Entity](https://tools.ietf.org/html/rfc2518#section-10.3)](https://tools.ietf.org/html/rfc2518#section-10.3) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称    | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ------- | ------ | ---- | ---- | ------ | ---- |
| » token | string | true | none |        | none |

状态码 **422**

| 名称  | 类型   | 必选 | 约束 | 中文名 | 说明 |
| ----- | ------ | ---- | ---- | ------ | ---- |
| » err | string | true | none |        | none |

## POST 用户修改信息

POST /user/alter

用户个人界面，自由修改信息。

> Body 请求参数

```json
{
  "username": "string",
  "sex": "string",
  "profile": {},
  "address": "string"
}
```

### 请求参数

| 名称       | 位置 | 类型   | 必选 | 中文名 | 说明 |
| ---------- | ---- | ------ | ---- | ------ | ---- |
| body       | body | object | 否   |        | none |
| » username | body | string | 是   |        | none |
| » sex      | body | string | 是   |        | none |
| » profile  | body | object | 是   | 头像   | none |
| » address  | body | string | 是   |        | none |

> 返回示例

> 200 Response

```json
{}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

# 商城主页

## GET 商品展示数据获取

GET /shop/query

全部商品获取，返回商品id列表，需要再以商品id列表逐一请求商品缩略介绍
疑问：疑似与搜索部分重合，同时不足以作为商城主页展示的内容

### 请求参数

| 名称       | 位置  | 类型   | 必选 | 中文名 | 说明 |
| ---------- | ----- | ------ | ---- | ------ | ---- |
| categories | query | string | 否   |        | none |
| pages      | query | string | 否   |        | none |
| token      | query | string | 否   |        | none |

> 返回示例

> 200 Response

```json
{
  "commodity_id_list": [
    0
  ]
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称                | 类型      | 必选 | 约束 | 中文名 | 说明 |
| ------------------- | --------- | ---- | ---- | ------ | ---- |
| » commodity_id_list | [integer] | true | none |        | none |

# 搜索结果

## GET 按搜索内容、tag筛选

GET /commondity/search

搜索页面的请求，同样返回id列表

### 请求参数

| 名称        | 位置  | 类型   | 必选 | 中文名 | 说明                 |
| ----------- | ----- | ------ | ---- | ------ | -------------------- |
| search      | query | string | 否   |        | none                 |
| categories  | query | string | 否   |        | none                 |
| restriction | query | string | 否   |        | 不会写，可能要正则？ |
| token       | query | string | 否   |        | none                 |

> 返回示例

> 200 Response

```json
{
  "commodity_id_list": [
    0
  ]
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称                | 类型      | 必选 | 约束 | 中文名 | 说明 |
| ------------------- | --------- | ---- | ---- | ------ | ---- |
| » commodity_id_list | [integer] | true | none |        | none |

# 商品详情

## GET 获取单个商品的详情

GET /commodity/detail

### 请求参数

| 名称         | 位置  | 类型    | 必选 | 中文名 | 说明 |
| ------------ | ----- | ------- | ---- | ------ | ---- |
| commodity_id | query | integer | 否   |        | none |
| token        | query | string  | 否   |        | none |

> 返回示例

> 200 Response

```json
{
  "name": "string",
  "price": 0,
  "detail": {},
  "intro": "string"
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称     | 类型    | 必选 | 约束 | 中文名 | 说明             |
| -------- | ------- | ---- | ---- | ------ | ---------------- |
| » name   | string  | true | none |        | 名称             |
| » price  | integer | true | none |        | 价格             |
| » detail | object  | true | none |        | 详细图片所在地址 |
| » intro  | string  | true | none |        | 简介             |

## GET 商品缩略介绍

GET /commidity/preview

### 请求参数

| 名称         | 位置  | 类型   | 必选 | 中文名 | 说明 |
| ------------ | ----- | ------ | ---- | ------ | ---- |
| commodity_id | query | string | 否   |        | none |
| token        | query | string | 否   |        | none |

> 返回示例

> 200 Response

```json
{
  "name": "string",
  "price": 0,
  "preview": {}
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称      | 类型    | 必选 | 约束 | 中文名 | 说明               |
| --------- | ------- | ---- | ---- | ------ | ------------------ |
| » name    | string  | true | none |        | 名称               |
| » price   | integer | true | none |        | 价格               |
| » preview | object  | true | none |        | 预览图片所在地址？ |

# 购物车

## POST 加入购物车

POST /cart/add

> Body 请求参数

```yaml
id: ""

```

### 请求参数

| 名称 | 位置 | 类型   | 必选 | 中文名 | 说明    |
| ---- | ---- | ------ | ---- | ------ | ------- |
| body | body | object | 否   |        | none    |
| » id | body | string | 否   |        | ID 编号 |

> 返回示例

> 200 Response

```json
{}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

## POST 移出购物车

POST /cart/delete

> Body 请求参数

```yaml
id: ""

```

### 请求参数

| 名称 | 位置  | 类型   | 必选 | 中文名 | 说明    |
| ---- | ----- | ------ | ---- | ------ | ------- |
| id   | query | string | 否   |        | ID 编号 |
| body | body  | object | 否   |        | none    |
| » id | body  | string | 否   |        | ID 编号 |

> 返回示例

> 200 Response

```json
{}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

## GET 获取购物车列表

GET /cart/query

返回商品id的列表，需要再调用缩略图展示

### 请求参数

| 名称  | 位置  | 类型   | 必选 | 中文名 | 说明 |
| ----- | ----- | ------ | ---- | ------ | ---- |
| token | query | string | 否   |        | none |
| page  | query | string | 否   |        | none |

> 返回示例

> 200 Response

```json
{
  "cart": [
    0
  ]
}
```

### 返回结果

| 状态码 | 状态码含义                                              | 说明 | 数据模型 |
| ------ | ------------------------------------------------------- | ---- | -------- |
| 200    | [[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)](https://tools.ietf.org/html/rfc7231#section-6.3.1) | none | Inline   |

### 返回数据结构

状态码 **200**

| 名称   | 类型      | 必选 | 约束 | 中文名 | 说明 |
| ------ | --------- | ---- | ---- | ------ | ---- |
| » cart | [integer] | true | none |        | none |

# 数据模型

<h2 id="tocS_commodity">commodity</h2>

<a id="schemacommodity"></a>
<a id="schema_commodity"></a>
<a id="tocScommodity"></a>
<a id="tocscommodity"></a>

```json
{
  "id": 0,
  "name": "string",
  "price": 0,
  "preview": {},
  "detail": {},
  "intro": "string"
}

```

### 属性

| 名称    | 类型    | 必选 | 约束 | 中文名 | 说明               |
| ------- | ------- | ---- | ---- | ------ | ------------------ |
| id      | integer | true | none |        | ID 编号            |
| name    | string  | true | none |        | 名称               |
| price   | integer | true | none |        | 价格               |
| preview | object  | true | none |        | 预览图片所在地址？ |
| detail  | object  | true | none |        | 详细图片所在地址   |
| intro   | string  | true | none |        | 简介               |

<h2 id="tocS_user">user</h2>

<a id="schemauser"></a>
<a id="schema_user"></a>
<a id="tocSuser"></a>
<a id="tocsuser"></a>

```json
{
  "userid": "string",
  "username": "string",
  "email": "string",
  "password": "string",
  "sex": "string",
  "profile": {},
  "address": "string"
}

```

### 属性

| 名称     | 类型   | 必选 | 约束 | 中文名 | 说明 |
| -------- | ------ | ---- | ---- | ------ | ---- |
| userid   | string | true | none |        | none |
| username | string | true | none |        | none |
| email    | string | true | none |        | none |
| password | string | true | none |        | none |
| sex      | string | true | none |        | none |
| profile  | object | true | none | 头像   | none |
| address  | string | true | none |        | none |

<h2 id="tocS_user_alter">user_alter</h2>

<a id="schemauser_alter"></a>
<a id="schema_user_alter"></a>
<a id="tocSuser_alter"></a>
<a id="tocsuser_alter"></a>

```json
{
  "username": "string",
  "sex": "string",
  "profile": {},
  "address": "string"
}

```

### 属性

| 名称     | 类型   | 必选 | 约束 | 中文名 | 说明 |
| -------- | ------ | ---- | ---- | ------ | ---- |
| username | string | true | none |        | none |
| sex      | string | true | none |        | none |
| profile  | object | true | none | 头像   | none |
| address  | string | true | none |        | none |

**Comment by BiDuang** [comment]
个人认为没有必要存储用户性别信息；

头像功能可暂缓添加；

地址等收货信息可另开表存储（允许用户持有多个地址）。
