### ISSUE TITLE
权限分级控制，多用户等级

### ISSUE THREAD

**Issue by BiDuang** [Greedy-Nattinessers/Shop-BE#4]
使用 OAuth2 和权限模型将用户划分为多等级身份，按照权限从大到小排列为:
- 管理员：开设账号，调整账号权限，管理商品；
- <del>商家：上/下架商品，修改商品信息；</del>
- 用户：下单商品，评论商品；
- 游客：搜索商品，查看商品信息；

其中高级的权限保证包含更低级的权限。

---
不再保留商家级权限，改为由管理员统一管理。

**Comment by xiao-kousaka** [comment]
评论商品是什么东西？api文档里没有。
应该先对api文档提出修改

**Comment by BiDuang** [comment]
> 评论商品是什么东西？api文档里没有。 应该先对api文档提出修改

指用户评价系统，可以先作为待定功能。放入一个较低的优先级队列等待处理。
